[config]
retention = 14
monitor-url = "https://uptime-kuma.example.com/api/push/ABCDEFGHIJ"

[[apps]]
name = "Example app"
containers = ["example_app"]

[[apps.mounts]]
origin = "POOL/apps/example_app"
destination = "/mnt/snapshots/example_app"
children = ["config"]

[[apps]]
name = "Another example app"
containers = ["another_example_app_db", "another_example_app"]

[[apps.mounts]]
origin = "POOL/apps/another_example_app"
destination = "/mnt/snapshots/another_example_app"
children = ["config", "data"]

[[apps.mounts]]
origin = "POOL/apps/another_example_app_db"
destination = "/mnt/snapshots/another_example_app_db"
children = ["data"]

[[apps]]
name = "An app with no containers to stop"
containers = []

[[apps.mounts]]
origin = "POOL/apps/container_that_should_not_shutdown"
destination = "/mnt/snapshots/container_that_should_not_shutdown"
children = ["config"]

[[apps]]
name = "An app with a top level mount only"
containers = ["top_level_mount_app"]

[[apps.mounts]]
origin = "POOL/apps/top_level_mount_app"
destination = "/mnt/snapshots/top_level_mount_app"
children = []
