[config]
retention = 14
backup-containers = ["borgmatic"]
monitor-url = "https://uptime-kuma.example.com/api/push/ABCDEFGHIJ"

[[apps]]
name = "Example app"
containers = ["example_app"]

[[apps.mounts]]
origin = "POOL/apps/example_app"
destination = "/mnt/snapshots/example_app"
children = ["config"]

[[apps]]
name = "Another example app"
containers = ["another_example_app_db", "another_example_app"]

[[apps.mounts]]
origin = "POOL/apps/another_example_app"
destination = "/mnt/snapshots/another_example_app"
children = ["config", "data"]

[[apps.mounts]]
origin = "POOL/apps/another_example_app_db"
destination = "/mnt/snapshots/another_example_app_db"
children = ["data"]
